### ISSUE TITLE
Model field renaming

### ISSUE THREAD

**Issue by bobbyesh** [etokrug/modua#29]
In the Definitions model, if we could change:

  'fk_sourcelang' -> 'language'
  'fk_definitionlang' -> 'target'
  'word_character' -> 'word'

We'll be able to let Django REST automatically handle URI's like:

/language/english/hello?target=chinese

Translating hello from English to Chinese.

**Comment by etokrug** [comment]
The REST framework doesn't allow for a string to represent it? Essentially force the call to go back, translate it from 'language' to 'fk_sourcelang'? I'll change it, because I think that style is more in line with how Django ORM column names are typically named, not the the "fk_" - that's a holdover from my MSSQL work. I'm just wondering in case we have a special case later.

**Comment by etokrug** [comment]
I've changed this in the newest models. Close when you can.

**Comment by bobbyesh** [comment]
REST framework offers a get_queryset() method that can be overridden, and that is exactly what we're doing right now.  But this change will allow us to not have to do that with every view access Definitions.
